[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

# 日本語対応のためのエンコーディング設定
[global]
developmentMode = false